packages:
  - ./packages/*
  - ./apps/*
onlyBuiltDependencies:
  - better-sqlite3
overrides:
  tar@<6.2.1: '>=6.2.1'
  undici@>=4.5.0 <5.28.5: '>=5.28.5'
  path-to-regexp@>=4.0.0 <6.3.0: '>=6.3.0'
  esbuild@<=0.24.2: '>=0.25.0'
  undici@<5.29.0: '>=5.29.0'
  form-data@>=4.0.0 <4.0.4: '>=4.0.4'
  tmp@<=0.2.3: '>=0.2.4'
