name: production

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout current repo state
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Load docs secrets
        uses: Infisical/secrets-action@v1.0.9
        with:
          method: universal
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          domain: ${{ secrets.INFISICAL_DOMAIN }}
          env-slug: production
          project-slug: grovine-docs
          export-type: env

      - name: Load backend secrets
        uses: Infisical/secrets-action@v1.0.9
        with:
          method: universal
          client-id: ${{ secrets.INFISICAL_CLIENT_ID }}
          client-secret: ${{ secrets.INFISICAL_CLIENT_SECRET }}
          domain: ${{ secrets.INFISICAL_DOMAIN }}
          env-slug: production
          project-slug: grovine-backend
          export-type: env

      - name: Install dependencies
        run: pnpm install

      - name: debug
        run: echo $VITE_NODE_ENV $VITE_BACKEND_URL

      - name: Build stack
        run: pnpm build

      - name: Test stack
        run: pnpm test

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push docs Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.docs
          push: true
          tags: adophilus/grovine-docs:production
          build-args: |
            "NODE_ENV=${{ env.NODE_ENV }}"
            "VITE_NODE_ENV=${{ env.VITE_NODE_ENV }}"
            "VITE_BACKEND_URL=${{ env.VITE_BACKEND_URL }}"
          platforms: linux/amd64

      - name: Build and push backend Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile.backend
          push: true
          tags: adophilus/grovine-backend:production
          build-args: |
            "NODE_ENV=${{ env.NODE_ENV }}"
          platforms: linux/amd64
