name: staging

on:
  pull_request:
    branches: [staging]
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout current repo state
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create output folder
        run: mkdir __site

      - name: Install dependencies
        run: pnpm install

      - name: Load .env file
        run: echo '${{ secrets.ENV }}' > .env

      - name: Build monorepo
        working-directory: packages
        run: |
          set -a            
          source .env
          set +a
          pnpm build

      - name: Move api docs to output folder
        run: |
          mkdir -p __site/docs/api
          cp -r apps/docs-api/dist/* __site/docs/api

      - name: Deploy docs
        working-directory: __site
        run: |
          mkdir -p .vercel/output/static
          echo '{ "version": 3 }' > .vercel/output/config.json
          mv docs/* .vercel/output/static
          nix run nixpkgs#bun -- x vercel deploy --prebuilt --target preview --token ${{ secrets.VERCEL_TOKEN }}
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_API_DOCS_PROJECT_ID }}

      - name: Deploy website
        working-directory: packages
        run: |
          set -a
          source .env
          set +a
          pnpm --filter @beta-lyfe/website run deploy --target preview
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEBSITE_PROJECT_ID }}

      - name: Deploy webapp
        working-directory: packages
        run: |
          set -a            
          source .env
          set +a
          pnpm --filter @beta-lyfe/webapp run deploy --target preview
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_WEBAPP_PROJECT_ID }}

      - name: Deploy standup backend
        working-directory: packages
        run: |
          set -a            
          source .env
          set +a
          pnpm --filter @beta-lyfe/standup-backend run deploy --target staging
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_STANDUP_BACKEND_PROJECT_ID }}

