name: staging

on:
  pull_request:
    branches: [main]
    types: [opened, synchronize, reopened]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [22]

    steps:
      - name: Checkout current repo state
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4
        with:
          version: 9.15.3

      - name: Setup bun
        uses: oven-sh/setup-bun@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}

      - name: Create output folder
        run: mkdir __site

      - name: Install dependencies
        run: pnpm install

      - name: Load .env file
        run: echo '${{ secrets.ENV_STAGING }}' > .env

      - name: Build monorepo
        run: |
          set -a
          source .env
          set +a
          pnpm build

      - name: Deploy docs
        run: |
          set -a
          source .env
          set +a
          cd apps/docs
          pnpm vercel:build && pnpm vercel:deploy --target preview
        env:
          VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
          VERCEL_PROJECT_ID: ${{ secrets.VERCEL_DOCS_PROJECT_ID }}
